#!/bin/bash
# shellcheck disable=SC1091
# shellcheck disable=SC2034
# shellcheck disable=SC2086
# shellcheck disable=SC2088
# shellcheck disable=SC2155

# Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"
ZSH_CUSTOM="$HOME/.config/omzsh"
ZSH_THEME="bira"

## --- Add HYPRDE to PATH
export HYPRDE="$HOME/.local/share/hyprde"
export PATH="$PATH:$HYPRDE/bin"

# Plugins
plugins=(
    ## --- Builtin
    composer
    copybuffer
    copyfile
    dirhistory
    dnf
    fzf
    ssh
    ssh-agent
    sudo
    vscode
    wp-cli

    ## --- Custom
    eza
    bin
    fast-syntax-highlighting
    hellwal
    laravel
    npm
    nvim
    zoxide
    zsh-autosuggestions
    zsh-syntax-highlighting
)

## --- Setup oh-my-zsh
source $ZSH/oh-my-zsh.sh

## --- zsh history
HISTFILE="~/.zsh_history"
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory

export LANG=en_US.UTF-8
export ARCHFLAGS="-arch $(uname -m)"